"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing MainFrame
class SCADAShutdownToolMainFrame( gui.MainFrame ):
	def __init__( self, parent ):
		gui.MainFrame.__init__( self, parent )
	
	# Handlers for MainFrame events.
	def exitFunc( self, event ):
		# TODO: Implement exitFunc
		pass
	
	def aboutFunc( self, event ):
		# TODO: Implement aboutFunc
		pass
	
	def start( self, event ):
		# TODO: Implement start
		pass
	
	
